steps:
- name: 'gcr.io/cloud-builders/gcloud'
  script: |
    gcloud run deploy cloudrunservice --image us-west2-docker.pkg.dev/mystic-bank-416419/quickpantry-docker-repo/quickpantry-image:tag1 --region us-west2 --platform managed --allow-unauthenticated